<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * irakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class irakRepository extends EntityRepository
{
}
